### ISSUE TITLE
Add prompt or guide for selecting transcripts

### ISSUE THREAD

**Issue by ghost** [C-Corbin/comfy_BED#6]
There is no prompt or guide allowing the user to see their transcript options. Possible pipeline-compatible implementation: Auto-populate a transcript choice flag, so that the user is provided a list of transcripts if they type an invalid transcript abbreviation.

**Comment by erikwaskiewicz** [comment]
I've been trying to think of the best way to do this, here's a few options:

1. Defaults to t1 if not set but if there are multiple transcripts then display an info message saying something along the lines of 'Transcripts available: t1, t2, t3. No transcript setting provided so making BED file for t1'

2. Required argument, have a separate flag that can be used to list all transcripts and exit the program, so that the user can get a list of transcripts. Or do that if there's an invalid input - I think that's what you suggested above?

3. Add a user prompt where they can select from a list, this would mean that the tool couldn't be used within a pipeline though

**Comment by ghost** [comment]
I prefer 1 or 2 over 3, as I'm envisioning this being used as a pipeline tool. I'm not sure which is best. I'd argue 2 is maybe safer, it forces the user to make a conscious choice and thus prevents people making mistakes via laziness, as people are tempted to just grab the BED that comes out without checking the transcript is right!

**Comment by ghost** [comment]
Solved.
